// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBStAOPRM6cuSIBB3KRhtpKycZ9nQOPr5w',
    appId: '1:191031982536:web:4c8dd470895caa075468fd',
    messagingSenderId: '191031982536',
    projectId: 'website-4fa8c',
    authDomain: 'website-4fa8c.firebaseapp.com',
    storageBucket: 'website-4fa8c.appspot.com',
    measurementId: 'G-MWSZG5D6GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJPnGEhyXzf2g3Rj0hrsqu1yOlFoDRkk',
    appId: '1:191031982536:android:7c833675c7edd0a95468fd',
    messagingSenderId: '191031982536',
    projectId: 'website-4fa8c',
    storageBucket: 'website-4fa8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfz6bi-jI3nttk42xWtxM6hMfPJXAzogc',
    appId: '1:191031982536:ios:649f069cabf948eb5468fd',
    messagingSenderId: '191031982536',
    projectId: 'website-4fa8c',
    storageBucket: 'website-4fa8c.appspot.com',
    iosBundleId: 'com.example.websiteProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfz6bi-jI3nttk42xWtxM6hMfPJXAzogc',
    appId: '1:191031982536:ios:649f069cabf948eb5468fd',
    messagingSenderId: '191031982536',
    projectId: 'website-4fa8c',
    storageBucket: 'website-4fa8c.appspot.com',
    iosBundleId: 'com.example.websiteProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBStAOPRM6cuSIBB3KRhtpKycZ9nQOPr5w',
    appId: '1:191031982536:web:bf83f328f09814485468fd',
    messagingSenderId: '191031982536',
    projectId: 'website-4fa8c',
    authDomain: 'website-4fa8c.firebaseapp.com',
    storageBucket: 'website-4fa8c.appspot.com',
    measurementId: 'G-2STLEKC2VL',
  );
}
